//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 11:21:39 PM BST 
//


package org.netbeans.ns.nb_module_project._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}code-name-base"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}suite-component"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}module-dependencies"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}public-packages"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codeNameBase",
    "suiteComponent",
    "moduleDependencies",
    "publicPackages"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(name = "code-name-base", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codeNameBase;
    @XmlElement(name = "suite-component", required = true)
    protected SuiteComponent suiteComponent;
    @XmlElement(name = "module-dependencies", required = true)
    protected ModuleDependencies moduleDependencies;
    @XmlElement(name = "public-packages", required = true)
    protected PublicPackages publicPackages;

    /**
     * Gets the value of the codeNameBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNameBase() {
        return codeNameBase;
    }

    /**
     * Sets the value of the codeNameBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNameBase(String value) {
        this.codeNameBase = value;
    }

    /**
     * Gets the value of the suiteComponent property.
     * 
     * @return
     *     possible object is
     *     {@link SuiteComponent }
     *     
     */
    public SuiteComponent getSuiteComponent() {
        return suiteComponent;
    }

    /**
     * Sets the value of the suiteComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuiteComponent }
     *     
     */
    public void setSuiteComponent(SuiteComponent value) {
        this.suiteComponent = value;
    }

    /**
     * Gets the value of the moduleDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleDependencies }
     *     
     */
    public ModuleDependencies getModuleDependencies() {
        return moduleDependencies;
    }

    /**
     * Sets the value of the moduleDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleDependencies }
     *     
     */
    public void setModuleDependencies(ModuleDependencies value) {
        this.moduleDependencies = value;
    }

    /**
     * Gets the value of the publicPackages property.
     * 
     * @return
     *     possible object is
     *     {@link PublicPackages }
     *     
     */
    public PublicPackages getPublicPackages() {
        return publicPackages;
    }

    /**
     * Sets the value of the publicPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicPackages }
     *     
     */
    public void setPublicPackages(PublicPackages value) {
        this.publicPackages = value;
    }

}
