//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 11:21:39 PM BST 
//


package org.netbeans.ns.nb_module_project._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}code-name-base"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}build-prerequisite"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}compile-dependency"/>
 *         &lt;element ref="{http://www.netbeans.org/ns/nb-module-project/3}run-dependency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codeNameBase",
    "buildPrerequisite",
    "compileDependency",
    "runDependency"
})
@XmlRootElement(name = "dependency")
public class Dependency {

    @XmlElement(name = "code-name-base", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codeNameBase;
    @XmlElement(name = "build-prerequisite", required = true)
    protected BuildPrerequisite buildPrerequisite;
    @XmlElement(name = "compile-dependency", required = true)
    protected CompileDependency compileDependency;
    @XmlElement(name = "run-dependency", required = true)
    protected RunDependency runDependency;

    /**
     * Gets the value of the codeNameBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNameBase() {
        return codeNameBase;
    }

    /**
     * Sets the value of the codeNameBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNameBase(String value) {
        this.codeNameBase = value;
    }

    /**
     * Gets the value of the buildPrerequisite property.
     * 
     * @return
     *     possible object is
     *     {@link BuildPrerequisite }
     *     
     */
    public BuildPrerequisite getBuildPrerequisite() {
        return buildPrerequisite;
    }

    /**
     * Sets the value of the buildPrerequisite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildPrerequisite }
     *     
     */
    public void setBuildPrerequisite(BuildPrerequisite value) {
        this.buildPrerequisite = value;
    }

    /**
     * Gets the value of the compileDependency property.
     * 
     * @return
     *     possible object is
     *     {@link CompileDependency }
     *     
     */
    public CompileDependency getCompileDependency() {
        return compileDependency;
    }

    /**
     * Sets the value of the compileDependency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompileDependency }
     *     
     */
    public void setCompileDependency(CompileDependency value) {
        this.compileDependency = value;
    }

    /**
     * Gets the value of the runDependency property.
     * 
     * @return
     *     possible object is
     *     {@link RunDependency }
     *     
     */
    public RunDependency getRunDependency() {
        return runDependency;
    }

    /**
     * Sets the value of the runDependency property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunDependency }
     *     
     */
    public void setRunDependency(RunDependency value) {
        this.runDependency = value;
    }

}
