//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 11:21:39 PM BST 
//

/**
 * I used trang to make a stab at the xsd for the NetBeans project.xml file and 
 * then used JAXB to generate the class file mappings.
 * 
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.netbeans.org/ns/nb-module-project/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.netbeans.ns.nb_module_project._3;
